# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: CloudDrive.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.protobuf.timestamp_pb2
import google.protobuf.empty_pb2
import CloudDrive_pb2


class CloudDriveFileSrvBase(abc.ABC):

    @abc.abstractmethod
    async def GetSystemInfo(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.CloudDriveSystemInfo]') -> None:
        pass

    @abc.abstractmethod
    async def GetToken(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.GetTokenRequest, CloudDrive_pb2.JWTToken]') -> None:
        pass

    @abc.abstractmethod
    async def Login(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.UserLoginRequest, CloudDrive_pb2.FileOperationResult]') -> None:
        pass

    @abc.abstractmethod
    async def Register(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.UserRegisterRequest, CloudDrive_pb2.FileOperationResult]') -> None:
        pass

    @abc.abstractmethod
    async def SendResetAccountEmail(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.SendResetAccountEmailRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def ResetAccount(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.ResetAccountRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def SendConfirmEmail(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def ConfirmEmail(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.ConfirmEmailRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def GetAccountStatus(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.AccountStatusResult]') -> None:
        pass

    @abc.abstractmethod
    async def GetSubFiles(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.ListSubFileRequest, CloudDrive_pb2.SubFilesReply]') -> None:
        pass

    @abc.abstractmethod
    async def GetSearchResults(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.SearchRequest, CloudDrive_pb2.SubFilesReply]') -> None:
        pass

    @abc.abstractmethod
    async def FindFileByPath(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.FindFileByPathRequest, CloudDrive_pb2.CloudDriveFile]') -> None:
        pass

    @abc.abstractmethod
    async def CreateFolder(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.CreateFolderRequest, CloudDrive_pb2.CreateFolderResult]') -> None:
        pass

    @abc.abstractmethod
    async def RenameFile(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.RenameFileRequest, CloudDrive_pb2.FileOperationResult]') -> None:
        pass

    @abc.abstractmethod
    async def RenameFiles(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.RenameFilesRequest, CloudDrive_pb2.FileOperationResult]') -> None:
        pass

    @abc.abstractmethod
    async def MoveFile(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.MoveFileRequest, CloudDrive_pb2.FileOperationResult]') -> None:
        pass

    @abc.abstractmethod
    async def DeleteFile(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.FileRequest, CloudDrive_pb2.FileOperationResult]') -> None:
        pass

    @abc.abstractmethod
    async def DeleteFilePermanently(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.FileRequest, CloudDrive_pb2.FileOperationResult]') -> None:
        pass

    @abc.abstractmethod
    async def DeleteFiles(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.MultiFileRequest, CloudDrive_pb2.FileOperationResult]') -> None:
        pass

    @abc.abstractmethod
    async def DeleteFilesPermanently(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.MultiFileRequest, CloudDrive_pb2.FileOperationResult]') -> None:
        pass

    @abc.abstractmethod
    async def AddOfflineFiles(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.AddOfflineFileRequest, CloudDrive_pb2.FileOperationResult]') -> None:
        pass

    @abc.abstractmethod
    async def RemoveOfflineFiles(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.RemoveOfflineFilesRequest, CloudDrive_pb2.FileOperationResult]') -> None:
        pass

    @abc.abstractmethod
    async def ListOfflineFilesByPath(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.FileRequest, CloudDrive_pb2.OfflineFileListResult]') -> None:
        pass

    @abc.abstractmethod
    async def ListAllOfflineFiles(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.OfflineFileListAllRequest, CloudDrive_pb2.OfflineFileListAllResult]') -> None:
        pass

    @abc.abstractmethod
    async def GetFileDetailProperties(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.FileRequest, CloudDrive_pb2.FileDetailProperties]') -> None:
        pass

    @abc.abstractmethod
    async def GetSpaceInfo(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.FileRequest, CloudDrive_pb2.SpaceInfo]') -> None:
        pass

    @abc.abstractmethod
    async def GetCloudMemberships(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.FileRequest, CloudDrive_pb2.CloudMemberships]') -> None:
        pass

    @abc.abstractmethod
    async def GetRuntimeInfo(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.RuntimeInfo]') -> None:
        pass

    @abc.abstractmethod
    async def GetRunningInfo(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.RunInfo]') -> None:
        pass

    @abc.abstractmethod
    async def Logout(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.UserLogoutRequest, CloudDrive_pb2.FileOperationResult]') -> None:
        pass

    @abc.abstractmethod
    async def CanAddMoreMountPoints(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.FileOperationResult]') -> None:
        pass

    @abc.abstractmethod
    async def GetMountPoints(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.GetMountPointsResult]') -> None:
        pass

    @abc.abstractmethod
    async def AddMountPoint(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.MountOption, CloudDrive_pb2.MountPointResult]') -> None:
        pass

    @abc.abstractmethod
    async def RemoveMountPoint(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.MountPointRequest, CloudDrive_pb2.MountPointResult]') -> None:
        pass

    @abc.abstractmethod
    async def Mount(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.MountPointRequest, CloudDrive_pb2.MountPointResult]') -> None:
        pass

    @abc.abstractmethod
    async def Unmount(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.MountPointRequest, CloudDrive_pb2.MountPointResult]') -> None:
        pass

    @abc.abstractmethod
    async def UpdateMountPoint(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.UpdateMountPointRequest, CloudDrive_pb2.MountPointResult]') -> None:
        pass

    @abc.abstractmethod
    async def GetAvailableDriveLetters(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.GetAvailableDriveLettersResult]') -> None:
        pass

    @abc.abstractmethod
    async def HasDriveLetters(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.HasDriveLettersResult]') -> None:
        pass

    @abc.abstractmethod
    async def LocalGetSubFiles(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.LocalGetSubFilesRequest, CloudDrive_pb2.LocalGetSubFilesResult]') -> None:
        pass

    @abc.abstractmethod
    async def GetAllTasksCount(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.GetAllTasksCountResult]') -> None:
        pass

    @abc.abstractmethod
    async def GetDownloadFileCount(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.GetDownloadFileCountResult]') -> None:
        pass

    @abc.abstractmethod
    async def GetDownloadFileList(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.GetDownloadFileListResult]') -> None:
        pass

    @abc.abstractmethod
    async def GetUploadFileCount(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.GetUploadFileCountResult]') -> None:
        pass

    @abc.abstractmethod
    async def GetUploadFileList(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.GetUploadFileListRequest, CloudDrive_pb2.GetUploadFileListResult]') -> None:
        pass

    @abc.abstractmethod
    async def CancelAllUploadFiles(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def CancelUploadFiles(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.MultpleUploadFileKeyRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def PauseAllUploadFiles(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def PauseUploadFiles(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.MultpleUploadFileKeyRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def ResumeAllUploadFiles(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def ResumeUploadFiles(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.MultpleUploadFileKeyRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def CanAddMoreCloudApis(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.FileOperationResult]') -> None:
        pass

    @abc.abstractmethod
    async def APILogin115Editthiscookie(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.Login115EditthiscookieRequest, CloudDrive_pb2.APILoginResult]') -> None:
        pass

    @abc.abstractmethod
    async def APILogin115QRCode(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.Login115QrCodeRequest, CloudDrive_pb2.QRCodeScanMessage]') -> None:
        pass

    @abc.abstractmethod
    async def APILoginAliyundriveOAuth(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.LoginAliyundriveOAuthRequest, CloudDrive_pb2.APILoginResult]') -> None:
        pass

    @abc.abstractmethod
    async def APILoginAliyundriveRefreshtoken(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.LoginAliyundriveRefreshtokenRequest, CloudDrive_pb2.APILoginResult]') -> None:
        pass

    @abc.abstractmethod
    async def APILoginAliyunDriveQRCode(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.LoginAliyundriveQRCodeRequest, CloudDrive_pb2.QRCodeScanMessage]') -> None:
        pass

    @abc.abstractmethod
    async def APILoginBaiduPanOAuth(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.LoginBaiduPanOAuthRequest, CloudDrive_pb2.APILoginResult]') -> None:
        pass

    @abc.abstractmethod
    async def APILoginOneDriveOAuth(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.LoginOneDriveOAuthRequest, CloudDrive_pb2.APILoginResult]') -> None:
        pass

    @abc.abstractmethod
    async def ApiLoginGoogleDriveOAuth(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.LoginGoogleDriveOAuthRequest, CloudDrive_pb2.APILoginResult]') -> None:
        pass

    @abc.abstractmethod
    async def ApiLoginGoogleDriveRefreshToken(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.LoginGoogleDriveRefreshTokenRequest, CloudDrive_pb2.APILoginResult]') -> None:
        pass

    @abc.abstractmethod
    async def ApiLoginXunleiOAuth(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.LoginXunleiOAuthRequest, CloudDrive_pb2.APILoginResult]') -> None:
        pass

    @abc.abstractmethod
    async def ApiLogin123panOAuth(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.Login123panOAuthRequest, CloudDrive_pb2.APILoginResult]') -> None:
        pass

    @abc.abstractmethod
    async def APILogin189QRCode(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.QRCodeScanMessage]') -> None:
        pass

    @abc.abstractmethod
    async def APILoginPikPak(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.UserLoginRequest, CloudDrive_pb2.APILoginResult]') -> None:
        pass

    @abc.abstractmethod
    async def APILoginWebDav(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.LoginWebDavRequest, CloudDrive_pb2.APILoginResult]') -> None:
        pass

    @abc.abstractmethod
    async def APIAddLocalFolder(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.AddLocalFolderRequest, CloudDrive_pb2.APILoginResult]') -> None:
        pass

    @abc.abstractmethod
    async def RemoveCloudAPI(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.RemoveCloudAPIRequest, CloudDrive_pb2.FileOperationResult]') -> None:
        pass

    @abc.abstractmethod
    async def GetAllCloudApis(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.CloudAPIList]') -> None:
        pass

    @abc.abstractmethod
    async def GetCloudAPIConfig(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.GetCloudAPIConfigRequest, CloudDrive_pb2.CloudAPIConfig]') -> None:
        pass

    @abc.abstractmethod
    async def SetCloudAPIConfig(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.SetCloudAPIConfigRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def GetSystemSettings(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.SystemSettings]') -> None:
        pass

    @abc.abstractmethod
    async def SetSystemSettings(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.SystemSettings, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def SetDirCacheTimeSecs(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.SetDirCacheTimeRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def GetEffectiveDirCacheTimeSecs(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.GetEffectiveDirCacheTimeRequest, CloudDrive_pb2.GetEffectiveDirCacheTimeResult]') -> None:
        pass

    @abc.abstractmethod
    async def GetOpenFileTable(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.GetOpenFileTableRequest, CloudDrive_pb2.OpenFileTable]') -> None:
        pass

    @abc.abstractmethod
    async def GetDirCacheTable(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.DirCacheTable]') -> None:
        pass

    @abc.abstractmethod
    async def GetReferencedEntryPaths(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.FileRequest, CloudDrive_pb2.StringList]') -> None:
        pass

    @abc.abstractmethod
    async def GetTempFileTable(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.TempFileTable]') -> None:
        pass

    @abc.abstractmethod
    async def PushTaskChange(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.GetAllTasksCountResult]') -> None:
        pass

    @abc.abstractmethod
    async def PushMessage(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.CloudDrivePushMessage]') -> None:
        pass

    @abc.abstractmethod
    async def GetCloudDrive1UserData(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.StringResult]') -> None:
        pass

    @abc.abstractmethod
    async def RestartService(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def ShutdownService(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def HasUpdate(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.UpdateResult]') -> None:
        pass

    @abc.abstractmethod
    async def CheckUpdate(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.UpdateResult]') -> None:
        pass

    @abc.abstractmethod
    async def DownloadUpdate(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def UpdateSystem(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def GetMetaData(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.FileRequest, CloudDrive_pb2.FileMetaData]') -> None:
        pass

    @abc.abstractmethod
    async def GetOriginalPath(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.FileRequest, CloudDrive_pb2.StringResult]') -> None:
        pass

    @abc.abstractmethod
    async def ChangePassword(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.ChangePasswordRequest, CloudDrive_pb2.FileOperationResult]') -> None:
        pass

    @abc.abstractmethod
    async def CreateFile(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.CreateFileRequest, CloudDrive_pb2.CreateFileResult]') -> None:
        pass

    @abc.abstractmethod
    async def CloseFile(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.CloseFileRequest, CloudDrive_pb2.FileOperationResult]') -> None:
        pass

    @abc.abstractmethod
    async def WriteToFileStream(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.WriteFileRequest, CloudDrive_pb2.WriteFileResult]') -> None:
        pass

    @abc.abstractmethod
    async def WriteToFile(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.WriteFileRequest, CloudDrive_pb2.WriteFileResult]') -> None:
        pass

    @abc.abstractmethod
    async def GetPromotions(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.GetPromotionsResult]') -> None:
        pass

    @abc.abstractmethod
    async def UpdatePromotionResult(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def GetCloudDrivePlans(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.GetCloudDrivePlansResult]') -> None:
        pass

    @abc.abstractmethod
    async def JoinPlan(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.JoinPlanRequest, CloudDrive_pb2.JoinPlanResult]') -> None:
        pass

    @abc.abstractmethod
    async def BindCloudAccount(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.BindCloudAccountRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def TransferBalance(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.TransferBalanceRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def ChangeEmail(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.ChangeUserNameEmailRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def GetBalanceLog(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.BalanceLogResult]') -> None:
        pass

    @abc.abstractmethod
    async def CheckActivationCode(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.StringValue, CloudDrive_pb2.CheckActivationCodeResult]') -> None:
        pass

    @abc.abstractmethod
    async def ActivatePlan(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.StringValue, CloudDrive_pb2.JoinPlanResult]') -> None:
        pass

    @abc.abstractmethod
    async def CheckCouponCode(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.CheckCouponCodeRequest, CloudDrive_pb2.CouponCodeResult]') -> None:
        pass

    @abc.abstractmethod
    async def GetReferralCode(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.StringValue]') -> None:
        pass

    @abc.abstractmethod
    async def BackupGetAll(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.BackupList]') -> None:
        pass

    @abc.abstractmethod
    async def BackupAdd(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.Backup, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def BackupRemove(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.StringValue, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def BackupUpdate(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.Backup, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def BackupAddDestination(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.BackupModifyRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def BackupRemoveDestination(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.BackupModifyRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def BackupSetEnabled(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.BackupSetEnabledRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def BackupSetFileSystemWatchEnabled(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.BackupModifyRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def BackupUpdateStrategies(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.BackupModifyRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def BackupRestartWalkingThrough(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.StringValue, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def CanAddMoreBackups(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.FileOperationResult]') -> None:
        pass

    @abc.abstractmethod
    async def GetMachineId(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.StringResult]') -> None:
        pass

    @abc.abstractmethod
    async def GetOnlineDevices(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, CloudDrive_pb2.OnlineDevices]') -> None:
        pass

    @abc.abstractmethod
    async def KickoutDevice(self, stream: 'grpclib.server.Stream[CloudDrive_pb2.DeviceRequest, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/clouddrive.CloudDriveFileSrv/GetSystemInfo': grpclib.const.Handler(
                self.GetSystemInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.CloudDriveSystemInfo,
            ),
            '/clouddrive.CloudDriveFileSrv/GetToken': grpclib.const.Handler(
                self.GetToken,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.GetTokenRequest,
                CloudDrive_pb2.JWTToken,
            ),
            '/clouddrive.CloudDriveFileSrv/Login': grpclib.const.Handler(
                self.Login,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.UserLoginRequest,
                CloudDrive_pb2.FileOperationResult,
            ),
            '/clouddrive.CloudDriveFileSrv/Register': grpclib.const.Handler(
                self.Register,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.UserRegisterRequest,
                CloudDrive_pb2.FileOperationResult,
            ),
            '/clouddrive.CloudDriveFileSrv/SendResetAccountEmail': grpclib.const.Handler(
                self.SendResetAccountEmail,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.SendResetAccountEmailRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/ResetAccount': grpclib.const.Handler(
                self.ResetAccount,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.ResetAccountRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/SendConfirmEmail': grpclib.const.Handler(
                self.SendConfirmEmail,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/ConfirmEmail': grpclib.const.Handler(
                self.ConfirmEmail,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.ConfirmEmailRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/GetAccountStatus': grpclib.const.Handler(
                self.GetAccountStatus,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.AccountStatusResult,
            ),
            '/clouddrive.CloudDriveFileSrv/GetSubFiles': grpclib.const.Handler(
                self.GetSubFiles,
                grpclib.const.Cardinality.UNARY_STREAM,
                CloudDrive_pb2.ListSubFileRequest,
                CloudDrive_pb2.SubFilesReply,
            ),
            '/clouddrive.CloudDriveFileSrv/GetSearchResults': grpclib.const.Handler(
                self.GetSearchResults,
                grpclib.const.Cardinality.UNARY_STREAM,
                CloudDrive_pb2.SearchRequest,
                CloudDrive_pb2.SubFilesReply,
            ),
            '/clouddrive.CloudDriveFileSrv/FindFileByPath': grpclib.const.Handler(
                self.FindFileByPath,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.FindFileByPathRequest,
                CloudDrive_pb2.CloudDriveFile,
            ),
            '/clouddrive.CloudDriveFileSrv/CreateFolder': grpclib.const.Handler(
                self.CreateFolder,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.CreateFolderRequest,
                CloudDrive_pb2.CreateFolderResult,
            ),
            '/clouddrive.CloudDriveFileSrv/RenameFile': grpclib.const.Handler(
                self.RenameFile,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.RenameFileRequest,
                CloudDrive_pb2.FileOperationResult,
            ),
            '/clouddrive.CloudDriveFileSrv/RenameFiles': grpclib.const.Handler(
                self.RenameFiles,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.RenameFilesRequest,
                CloudDrive_pb2.FileOperationResult,
            ),
            '/clouddrive.CloudDriveFileSrv/MoveFile': grpclib.const.Handler(
                self.MoveFile,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.MoveFileRequest,
                CloudDrive_pb2.FileOperationResult,
            ),
            '/clouddrive.CloudDriveFileSrv/DeleteFile': grpclib.const.Handler(
                self.DeleteFile,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.FileRequest,
                CloudDrive_pb2.FileOperationResult,
            ),
            '/clouddrive.CloudDriveFileSrv/DeleteFilePermanently': grpclib.const.Handler(
                self.DeleteFilePermanently,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.FileRequest,
                CloudDrive_pb2.FileOperationResult,
            ),
            '/clouddrive.CloudDriveFileSrv/DeleteFiles': grpclib.const.Handler(
                self.DeleteFiles,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.MultiFileRequest,
                CloudDrive_pb2.FileOperationResult,
            ),
            '/clouddrive.CloudDriveFileSrv/DeleteFilesPermanently': grpclib.const.Handler(
                self.DeleteFilesPermanently,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.MultiFileRequest,
                CloudDrive_pb2.FileOperationResult,
            ),
            '/clouddrive.CloudDriveFileSrv/AddOfflineFiles': grpclib.const.Handler(
                self.AddOfflineFiles,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.AddOfflineFileRequest,
                CloudDrive_pb2.FileOperationResult,
            ),
            '/clouddrive.CloudDriveFileSrv/RemoveOfflineFiles': grpclib.const.Handler(
                self.RemoveOfflineFiles,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.RemoveOfflineFilesRequest,
                CloudDrive_pb2.FileOperationResult,
            ),
            '/clouddrive.CloudDriveFileSrv/ListOfflineFilesByPath': grpclib.const.Handler(
                self.ListOfflineFilesByPath,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.FileRequest,
                CloudDrive_pb2.OfflineFileListResult,
            ),
            '/clouddrive.CloudDriveFileSrv/ListAllOfflineFiles': grpclib.const.Handler(
                self.ListAllOfflineFiles,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.OfflineFileListAllRequest,
                CloudDrive_pb2.OfflineFileListAllResult,
            ),
            '/clouddrive.CloudDriveFileSrv/GetFileDetailProperties': grpclib.const.Handler(
                self.GetFileDetailProperties,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.FileRequest,
                CloudDrive_pb2.FileDetailProperties,
            ),
            '/clouddrive.CloudDriveFileSrv/GetSpaceInfo': grpclib.const.Handler(
                self.GetSpaceInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.FileRequest,
                CloudDrive_pb2.SpaceInfo,
            ),
            '/clouddrive.CloudDriveFileSrv/GetCloudMemberships': grpclib.const.Handler(
                self.GetCloudMemberships,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.FileRequest,
                CloudDrive_pb2.CloudMemberships,
            ),
            '/clouddrive.CloudDriveFileSrv/GetRuntimeInfo': grpclib.const.Handler(
                self.GetRuntimeInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.RuntimeInfo,
            ),
            '/clouddrive.CloudDriveFileSrv/GetRunningInfo': grpclib.const.Handler(
                self.GetRunningInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.RunInfo,
            ),
            '/clouddrive.CloudDriveFileSrv/Logout': grpclib.const.Handler(
                self.Logout,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.UserLogoutRequest,
                CloudDrive_pb2.FileOperationResult,
            ),
            '/clouddrive.CloudDriveFileSrv/CanAddMoreMountPoints': grpclib.const.Handler(
                self.CanAddMoreMountPoints,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.FileOperationResult,
            ),
            '/clouddrive.CloudDriveFileSrv/GetMountPoints': grpclib.const.Handler(
                self.GetMountPoints,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.GetMountPointsResult,
            ),
            '/clouddrive.CloudDriveFileSrv/AddMountPoint': grpclib.const.Handler(
                self.AddMountPoint,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.MountOption,
                CloudDrive_pb2.MountPointResult,
            ),
            '/clouddrive.CloudDriveFileSrv/RemoveMountPoint': grpclib.const.Handler(
                self.RemoveMountPoint,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.MountPointRequest,
                CloudDrive_pb2.MountPointResult,
            ),
            '/clouddrive.CloudDriveFileSrv/Mount': grpclib.const.Handler(
                self.Mount,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.MountPointRequest,
                CloudDrive_pb2.MountPointResult,
            ),
            '/clouddrive.CloudDriveFileSrv/Unmount': grpclib.const.Handler(
                self.Unmount,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.MountPointRequest,
                CloudDrive_pb2.MountPointResult,
            ),
            '/clouddrive.CloudDriveFileSrv/UpdateMountPoint': grpclib.const.Handler(
                self.UpdateMountPoint,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.UpdateMountPointRequest,
                CloudDrive_pb2.MountPointResult,
            ),
            '/clouddrive.CloudDriveFileSrv/GetAvailableDriveLetters': grpclib.const.Handler(
                self.GetAvailableDriveLetters,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.GetAvailableDriveLettersResult,
            ),
            '/clouddrive.CloudDriveFileSrv/HasDriveLetters': grpclib.const.Handler(
                self.HasDriveLetters,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.HasDriveLettersResult,
            ),
            '/clouddrive.CloudDriveFileSrv/LocalGetSubFiles': grpclib.const.Handler(
                self.LocalGetSubFiles,
                grpclib.const.Cardinality.UNARY_STREAM,
                CloudDrive_pb2.LocalGetSubFilesRequest,
                CloudDrive_pb2.LocalGetSubFilesResult,
            ),
            '/clouddrive.CloudDriveFileSrv/GetAllTasksCount': grpclib.const.Handler(
                self.GetAllTasksCount,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.GetAllTasksCountResult,
            ),
            '/clouddrive.CloudDriveFileSrv/GetDownloadFileCount': grpclib.const.Handler(
                self.GetDownloadFileCount,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.GetDownloadFileCountResult,
            ),
            '/clouddrive.CloudDriveFileSrv/GetDownloadFileList': grpclib.const.Handler(
                self.GetDownloadFileList,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.GetDownloadFileListResult,
            ),
            '/clouddrive.CloudDriveFileSrv/GetUploadFileCount': grpclib.const.Handler(
                self.GetUploadFileCount,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.GetUploadFileCountResult,
            ),
            '/clouddrive.CloudDriveFileSrv/GetUploadFileList': grpclib.const.Handler(
                self.GetUploadFileList,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.GetUploadFileListRequest,
                CloudDrive_pb2.GetUploadFileListResult,
            ),
            '/clouddrive.CloudDriveFileSrv/CancelAllUploadFiles': grpclib.const.Handler(
                self.CancelAllUploadFiles,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/CancelUploadFiles': grpclib.const.Handler(
                self.CancelUploadFiles,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.MultpleUploadFileKeyRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/PauseAllUploadFiles': grpclib.const.Handler(
                self.PauseAllUploadFiles,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/PauseUploadFiles': grpclib.const.Handler(
                self.PauseUploadFiles,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.MultpleUploadFileKeyRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/ResumeAllUploadFiles': grpclib.const.Handler(
                self.ResumeAllUploadFiles,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/ResumeUploadFiles': grpclib.const.Handler(
                self.ResumeUploadFiles,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.MultpleUploadFileKeyRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/CanAddMoreCloudApis': grpclib.const.Handler(
                self.CanAddMoreCloudApis,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.FileOperationResult,
            ),
            '/clouddrive.CloudDriveFileSrv/APILogin115Editthiscookie': grpclib.const.Handler(
                self.APILogin115Editthiscookie,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.Login115EditthiscookieRequest,
                CloudDrive_pb2.APILoginResult,
            ),
            '/clouddrive.CloudDriveFileSrv/APILogin115QRCode': grpclib.const.Handler(
                self.APILogin115QRCode,
                grpclib.const.Cardinality.UNARY_STREAM,
                CloudDrive_pb2.Login115QrCodeRequest,
                CloudDrive_pb2.QRCodeScanMessage,
            ),
            '/clouddrive.CloudDriveFileSrv/APILoginAliyundriveOAuth': grpclib.const.Handler(
                self.APILoginAliyundriveOAuth,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.LoginAliyundriveOAuthRequest,
                CloudDrive_pb2.APILoginResult,
            ),
            '/clouddrive.CloudDriveFileSrv/APILoginAliyundriveRefreshtoken': grpclib.const.Handler(
                self.APILoginAliyundriveRefreshtoken,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.LoginAliyundriveRefreshtokenRequest,
                CloudDrive_pb2.APILoginResult,
            ),
            '/clouddrive.CloudDriveFileSrv/APILoginAliyunDriveQRCode': grpclib.const.Handler(
                self.APILoginAliyunDriveQRCode,
                grpclib.const.Cardinality.UNARY_STREAM,
                CloudDrive_pb2.LoginAliyundriveQRCodeRequest,
                CloudDrive_pb2.QRCodeScanMessage,
            ),
            '/clouddrive.CloudDriveFileSrv/APILoginBaiduPanOAuth': grpclib.const.Handler(
                self.APILoginBaiduPanOAuth,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.LoginBaiduPanOAuthRequest,
                CloudDrive_pb2.APILoginResult,
            ),
            '/clouddrive.CloudDriveFileSrv/APILoginOneDriveOAuth': grpclib.const.Handler(
                self.APILoginOneDriveOAuth,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.LoginOneDriveOAuthRequest,
                CloudDrive_pb2.APILoginResult,
            ),
            '/clouddrive.CloudDriveFileSrv/ApiLoginGoogleDriveOAuth': grpclib.const.Handler(
                self.ApiLoginGoogleDriveOAuth,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.LoginGoogleDriveOAuthRequest,
                CloudDrive_pb2.APILoginResult,
            ),
            '/clouddrive.CloudDriveFileSrv/ApiLoginGoogleDriveRefreshToken': grpclib.const.Handler(
                self.ApiLoginGoogleDriveRefreshToken,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.LoginGoogleDriveRefreshTokenRequest,
                CloudDrive_pb2.APILoginResult,
            ),
            '/clouddrive.CloudDriveFileSrv/ApiLoginXunleiOAuth': grpclib.const.Handler(
                self.ApiLoginXunleiOAuth,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.LoginXunleiOAuthRequest,
                CloudDrive_pb2.APILoginResult,
            ),
            '/clouddrive.CloudDriveFileSrv/ApiLogin123panOAuth': grpclib.const.Handler(
                self.ApiLogin123panOAuth,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.Login123panOAuthRequest,
                CloudDrive_pb2.APILoginResult,
            ),
            '/clouddrive.CloudDriveFileSrv/APILogin189QRCode': grpclib.const.Handler(
                self.APILogin189QRCode,
                grpclib.const.Cardinality.UNARY_STREAM,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.QRCodeScanMessage,
            ),
            '/clouddrive.CloudDriveFileSrv/APILoginPikPak': grpclib.const.Handler(
                self.APILoginPikPak,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.UserLoginRequest,
                CloudDrive_pb2.APILoginResult,
            ),
            '/clouddrive.CloudDriveFileSrv/APILoginWebDav': grpclib.const.Handler(
                self.APILoginWebDav,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.LoginWebDavRequest,
                CloudDrive_pb2.APILoginResult,
            ),
            '/clouddrive.CloudDriveFileSrv/APIAddLocalFolder': grpclib.const.Handler(
                self.APIAddLocalFolder,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.AddLocalFolderRequest,
                CloudDrive_pb2.APILoginResult,
            ),
            '/clouddrive.CloudDriveFileSrv/RemoveCloudAPI': grpclib.const.Handler(
                self.RemoveCloudAPI,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.RemoveCloudAPIRequest,
                CloudDrive_pb2.FileOperationResult,
            ),
            '/clouddrive.CloudDriveFileSrv/GetAllCloudApis': grpclib.const.Handler(
                self.GetAllCloudApis,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.CloudAPIList,
            ),
            '/clouddrive.CloudDriveFileSrv/GetCloudAPIConfig': grpclib.const.Handler(
                self.GetCloudAPIConfig,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.GetCloudAPIConfigRequest,
                CloudDrive_pb2.CloudAPIConfig,
            ),
            '/clouddrive.CloudDriveFileSrv/SetCloudAPIConfig': grpclib.const.Handler(
                self.SetCloudAPIConfig,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.SetCloudAPIConfigRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/GetSystemSettings': grpclib.const.Handler(
                self.GetSystemSettings,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.SystemSettings,
            ),
            '/clouddrive.CloudDriveFileSrv/SetSystemSettings': grpclib.const.Handler(
                self.SetSystemSettings,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.SystemSettings,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/SetDirCacheTimeSecs': grpclib.const.Handler(
                self.SetDirCacheTimeSecs,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.SetDirCacheTimeRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/GetEffectiveDirCacheTimeSecs': grpclib.const.Handler(
                self.GetEffectiveDirCacheTimeSecs,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.GetEffectiveDirCacheTimeRequest,
                CloudDrive_pb2.GetEffectiveDirCacheTimeResult,
            ),
            '/clouddrive.CloudDriveFileSrv/GetOpenFileTable': grpclib.const.Handler(
                self.GetOpenFileTable,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.GetOpenFileTableRequest,
                CloudDrive_pb2.OpenFileTable,
            ),
            '/clouddrive.CloudDriveFileSrv/GetDirCacheTable': grpclib.const.Handler(
                self.GetDirCacheTable,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.DirCacheTable,
            ),
            '/clouddrive.CloudDriveFileSrv/GetReferencedEntryPaths': grpclib.const.Handler(
                self.GetReferencedEntryPaths,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.FileRequest,
                CloudDrive_pb2.StringList,
            ),
            '/clouddrive.CloudDriveFileSrv/GetTempFileTable': grpclib.const.Handler(
                self.GetTempFileTable,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.TempFileTable,
            ),
            '/clouddrive.CloudDriveFileSrv/PushTaskChange': grpclib.const.Handler(
                self.PushTaskChange,
                grpclib.const.Cardinality.UNARY_STREAM,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.GetAllTasksCountResult,
            ),
            '/clouddrive.CloudDriveFileSrv/PushMessage': grpclib.const.Handler(
                self.PushMessage,
                grpclib.const.Cardinality.UNARY_STREAM,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.CloudDrivePushMessage,
            ),
            '/clouddrive.CloudDriveFileSrv/GetCloudDrive1UserData': grpclib.const.Handler(
                self.GetCloudDrive1UserData,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.StringResult,
            ),
            '/clouddrive.CloudDriveFileSrv/RestartService': grpclib.const.Handler(
                self.RestartService,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/ShutdownService': grpclib.const.Handler(
                self.ShutdownService,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/HasUpdate': grpclib.const.Handler(
                self.HasUpdate,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.UpdateResult,
            ),
            '/clouddrive.CloudDriveFileSrv/CheckUpdate': grpclib.const.Handler(
                self.CheckUpdate,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.UpdateResult,
            ),
            '/clouddrive.CloudDriveFileSrv/DownloadUpdate': grpclib.const.Handler(
                self.DownloadUpdate,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/UpdateSystem': grpclib.const.Handler(
                self.UpdateSystem,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/GetMetaData': grpclib.const.Handler(
                self.GetMetaData,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.FileRequest,
                CloudDrive_pb2.FileMetaData,
            ),
            '/clouddrive.CloudDriveFileSrv/GetOriginalPath': grpclib.const.Handler(
                self.GetOriginalPath,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.FileRequest,
                CloudDrive_pb2.StringResult,
            ),
            '/clouddrive.CloudDriveFileSrv/ChangePassword': grpclib.const.Handler(
                self.ChangePassword,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.ChangePasswordRequest,
                CloudDrive_pb2.FileOperationResult,
            ),
            '/clouddrive.CloudDriveFileSrv/CreateFile': grpclib.const.Handler(
                self.CreateFile,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.CreateFileRequest,
                CloudDrive_pb2.CreateFileResult,
            ),
            '/clouddrive.CloudDriveFileSrv/CloseFile': grpclib.const.Handler(
                self.CloseFile,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.CloseFileRequest,
                CloudDrive_pb2.FileOperationResult,
            ),
            '/clouddrive.CloudDriveFileSrv/WriteToFileStream': grpclib.const.Handler(
                self.WriteToFileStream,
                grpclib.const.Cardinality.STREAM_UNARY,
                CloudDrive_pb2.WriteFileRequest,
                CloudDrive_pb2.WriteFileResult,
            ),
            '/clouddrive.CloudDriveFileSrv/WriteToFile': grpclib.const.Handler(
                self.WriteToFile,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.WriteFileRequest,
                CloudDrive_pb2.WriteFileResult,
            ),
            '/clouddrive.CloudDriveFileSrv/GetPromotions': grpclib.const.Handler(
                self.GetPromotions,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.GetPromotionsResult,
            ),
            '/clouddrive.CloudDriveFileSrv/UpdatePromotionResult': grpclib.const.Handler(
                self.UpdatePromotionResult,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/GetCloudDrivePlans': grpclib.const.Handler(
                self.GetCloudDrivePlans,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.GetCloudDrivePlansResult,
            ),
            '/clouddrive.CloudDriveFileSrv/JoinPlan': grpclib.const.Handler(
                self.JoinPlan,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.JoinPlanRequest,
                CloudDrive_pb2.JoinPlanResult,
            ),
            '/clouddrive.CloudDriveFileSrv/BindCloudAccount': grpclib.const.Handler(
                self.BindCloudAccount,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.BindCloudAccountRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/TransferBalance': grpclib.const.Handler(
                self.TransferBalance,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.TransferBalanceRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/ChangeEmail': grpclib.const.Handler(
                self.ChangeEmail,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.ChangeUserNameEmailRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/GetBalanceLog': grpclib.const.Handler(
                self.GetBalanceLog,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.BalanceLogResult,
            ),
            '/clouddrive.CloudDriveFileSrv/CheckActivationCode': grpclib.const.Handler(
                self.CheckActivationCode,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.StringValue,
                CloudDrive_pb2.CheckActivationCodeResult,
            ),
            '/clouddrive.CloudDriveFileSrv/ActivatePlan': grpclib.const.Handler(
                self.ActivatePlan,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.StringValue,
                CloudDrive_pb2.JoinPlanResult,
            ),
            '/clouddrive.CloudDriveFileSrv/CheckCouponCode': grpclib.const.Handler(
                self.CheckCouponCode,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.CheckCouponCodeRequest,
                CloudDrive_pb2.CouponCodeResult,
            ),
            '/clouddrive.CloudDriveFileSrv/GetReferralCode': grpclib.const.Handler(
                self.GetReferralCode,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.StringValue,
            ),
            '/clouddrive.CloudDriveFileSrv/BackupGetAll': grpclib.const.Handler(
                self.BackupGetAll,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.BackupList,
            ),
            '/clouddrive.CloudDriveFileSrv/BackupAdd': grpclib.const.Handler(
                self.BackupAdd,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.Backup,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/BackupRemove': grpclib.const.Handler(
                self.BackupRemove,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.StringValue,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/BackupUpdate': grpclib.const.Handler(
                self.BackupUpdate,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.Backup,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/BackupAddDestination': grpclib.const.Handler(
                self.BackupAddDestination,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.BackupModifyRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/BackupRemoveDestination': grpclib.const.Handler(
                self.BackupRemoveDestination,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.BackupModifyRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/BackupSetEnabled': grpclib.const.Handler(
                self.BackupSetEnabled,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.BackupSetEnabledRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/BackupSetFileSystemWatchEnabled': grpclib.const.Handler(
                self.BackupSetFileSystemWatchEnabled,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.BackupModifyRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/BackupUpdateStrategies': grpclib.const.Handler(
                self.BackupUpdateStrategies,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.BackupModifyRequest,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/BackupRestartWalkingThrough': grpclib.const.Handler(
                self.BackupRestartWalkingThrough,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.StringValue,
                google.protobuf.empty_pb2.Empty,
            ),
            '/clouddrive.CloudDriveFileSrv/CanAddMoreBackups': grpclib.const.Handler(
                self.CanAddMoreBackups,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.FileOperationResult,
            ),
            '/clouddrive.CloudDriveFileSrv/GetMachineId': grpclib.const.Handler(
                self.GetMachineId,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.StringResult,
            ),
            '/clouddrive.CloudDriveFileSrv/GetOnlineDevices': grpclib.const.Handler(
                self.GetOnlineDevices,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                CloudDrive_pb2.OnlineDevices,
            ),
            '/clouddrive.CloudDriveFileSrv/KickoutDevice': grpclib.const.Handler(
                self.KickoutDevice,
                grpclib.const.Cardinality.UNARY_UNARY,
                CloudDrive_pb2.DeviceRequest,
                google.protobuf.empty_pb2.Empty,
            ),
        }


class CloudDriveFileSrvStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetSystemInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetSystemInfo',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.CloudDriveSystemInfo,
        )
        self.GetToken = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetToken',
            CloudDrive_pb2.GetTokenRequest,
            CloudDrive_pb2.JWTToken,
        )
        self.Login = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/Login',
            CloudDrive_pb2.UserLoginRequest,
            CloudDrive_pb2.FileOperationResult,
        )
        self.Register = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/Register',
            CloudDrive_pb2.UserRegisterRequest,
            CloudDrive_pb2.FileOperationResult,
        )
        self.SendResetAccountEmail = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/SendResetAccountEmail',
            CloudDrive_pb2.SendResetAccountEmailRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.ResetAccount = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/ResetAccount',
            CloudDrive_pb2.ResetAccountRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.SendConfirmEmail = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/SendConfirmEmail',
            google.protobuf.empty_pb2.Empty,
            google.protobuf.empty_pb2.Empty,
        )
        self.ConfirmEmail = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/ConfirmEmail',
            CloudDrive_pb2.ConfirmEmailRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.GetAccountStatus = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetAccountStatus',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.AccountStatusResult,
        )
        self.GetSubFiles = grpclib.client.UnaryStreamMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetSubFiles',
            CloudDrive_pb2.ListSubFileRequest,
            CloudDrive_pb2.SubFilesReply,
        )
        self.GetSearchResults = grpclib.client.UnaryStreamMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetSearchResults',
            CloudDrive_pb2.SearchRequest,
            CloudDrive_pb2.SubFilesReply,
        )
        self.FindFileByPath = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/FindFileByPath',
            CloudDrive_pb2.FindFileByPathRequest,
            CloudDrive_pb2.CloudDriveFile,
        )
        self.CreateFolder = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/CreateFolder',
            CloudDrive_pb2.CreateFolderRequest,
            CloudDrive_pb2.CreateFolderResult,
        )
        self.RenameFile = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/RenameFile',
            CloudDrive_pb2.RenameFileRequest,
            CloudDrive_pb2.FileOperationResult,
        )
        self.RenameFiles = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/RenameFiles',
            CloudDrive_pb2.RenameFilesRequest,
            CloudDrive_pb2.FileOperationResult,
        )
        self.MoveFile = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/MoveFile',
            CloudDrive_pb2.MoveFileRequest,
            CloudDrive_pb2.FileOperationResult,
        )
        self.DeleteFile = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/DeleteFile',
            CloudDrive_pb2.FileRequest,
            CloudDrive_pb2.FileOperationResult,
        )
        self.DeleteFilePermanently = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/DeleteFilePermanently',
            CloudDrive_pb2.FileRequest,
            CloudDrive_pb2.FileOperationResult,
        )
        self.DeleteFiles = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/DeleteFiles',
            CloudDrive_pb2.MultiFileRequest,
            CloudDrive_pb2.FileOperationResult,
        )
        self.DeleteFilesPermanently = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/DeleteFilesPermanently',
            CloudDrive_pb2.MultiFileRequest,
            CloudDrive_pb2.FileOperationResult,
        )
        self.AddOfflineFiles = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/AddOfflineFiles',
            CloudDrive_pb2.AddOfflineFileRequest,
            CloudDrive_pb2.FileOperationResult,
        )
        self.RemoveOfflineFiles = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/RemoveOfflineFiles',
            CloudDrive_pb2.RemoveOfflineFilesRequest,
            CloudDrive_pb2.FileOperationResult,
        )
        self.ListOfflineFilesByPath = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/ListOfflineFilesByPath',
            CloudDrive_pb2.FileRequest,
            CloudDrive_pb2.OfflineFileListResult,
        )
        self.ListAllOfflineFiles = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/ListAllOfflineFiles',
            CloudDrive_pb2.OfflineFileListAllRequest,
            CloudDrive_pb2.OfflineFileListAllResult,
        )
        self.GetFileDetailProperties = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetFileDetailProperties',
            CloudDrive_pb2.FileRequest,
            CloudDrive_pb2.FileDetailProperties,
        )
        self.GetSpaceInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetSpaceInfo',
            CloudDrive_pb2.FileRequest,
            CloudDrive_pb2.SpaceInfo,
        )
        self.GetCloudMemberships = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetCloudMemberships',
            CloudDrive_pb2.FileRequest,
            CloudDrive_pb2.CloudMemberships,
        )
        self.GetRuntimeInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetRuntimeInfo',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.RuntimeInfo,
        )
        self.GetRunningInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetRunningInfo',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.RunInfo,
        )
        self.Logout = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/Logout',
            CloudDrive_pb2.UserLogoutRequest,
            CloudDrive_pb2.FileOperationResult,
        )
        self.CanAddMoreMountPoints = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/CanAddMoreMountPoints',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.FileOperationResult,
        )
        self.GetMountPoints = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetMountPoints',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.GetMountPointsResult,
        )
        self.AddMountPoint = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/AddMountPoint',
            CloudDrive_pb2.MountOption,
            CloudDrive_pb2.MountPointResult,
        )
        self.RemoveMountPoint = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/RemoveMountPoint',
            CloudDrive_pb2.MountPointRequest,
            CloudDrive_pb2.MountPointResult,
        )
        self.Mount = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/Mount',
            CloudDrive_pb2.MountPointRequest,
            CloudDrive_pb2.MountPointResult,
        )
        self.Unmount = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/Unmount',
            CloudDrive_pb2.MountPointRequest,
            CloudDrive_pb2.MountPointResult,
        )
        self.UpdateMountPoint = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/UpdateMountPoint',
            CloudDrive_pb2.UpdateMountPointRequest,
            CloudDrive_pb2.MountPointResult,
        )
        self.GetAvailableDriveLetters = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetAvailableDriveLetters',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.GetAvailableDriveLettersResult,
        )
        self.HasDriveLetters = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/HasDriveLetters',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.HasDriveLettersResult,
        )
        self.LocalGetSubFiles = grpclib.client.UnaryStreamMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/LocalGetSubFiles',
            CloudDrive_pb2.LocalGetSubFilesRequest,
            CloudDrive_pb2.LocalGetSubFilesResult,
        )
        self.GetAllTasksCount = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetAllTasksCount',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.GetAllTasksCountResult,
        )
        self.GetDownloadFileCount = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetDownloadFileCount',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.GetDownloadFileCountResult,
        )
        self.GetDownloadFileList = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetDownloadFileList',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.GetDownloadFileListResult,
        )
        self.GetUploadFileCount = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetUploadFileCount',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.GetUploadFileCountResult,
        )
        self.GetUploadFileList = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetUploadFileList',
            CloudDrive_pb2.GetUploadFileListRequest,
            CloudDrive_pb2.GetUploadFileListResult,
        )
        self.CancelAllUploadFiles = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/CancelAllUploadFiles',
            google.protobuf.empty_pb2.Empty,
            google.protobuf.empty_pb2.Empty,
        )
        self.CancelUploadFiles = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/CancelUploadFiles',
            CloudDrive_pb2.MultpleUploadFileKeyRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.PauseAllUploadFiles = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/PauseAllUploadFiles',
            google.protobuf.empty_pb2.Empty,
            google.protobuf.empty_pb2.Empty,
        )
        self.PauseUploadFiles = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/PauseUploadFiles',
            CloudDrive_pb2.MultpleUploadFileKeyRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.ResumeAllUploadFiles = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/ResumeAllUploadFiles',
            google.protobuf.empty_pb2.Empty,
            google.protobuf.empty_pb2.Empty,
        )
        self.ResumeUploadFiles = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/ResumeUploadFiles',
            CloudDrive_pb2.MultpleUploadFileKeyRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.CanAddMoreCloudApis = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/CanAddMoreCloudApis',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.FileOperationResult,
        )
        self.APILogin115Editthiscookie = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/APILogin115Editthiscookie',
            CloudDrive_pb2.Login115EditthiscookieRequest,
            CloudDrive_pb2.APILoginResult,
        )
        self.APILogin115QRCode = grpclib.client.UnaryStreamMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/APILogin115QRCode',
            CloudDrive_pb2.Login115QrCodeRequest,
            CloudDrive_pb2.QRCodeScanMessage,
        )
        self.APILoginAliyundriveOAuth = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/APILoginAliyundriveOAuth',
            CloudDrive_pb2.LoginAliyundriveOAuthRequest,
            CloudDrive_pb2.APILoginResult,
        )
        self.APILoginAliyundriveRefreshtoken = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/APILoginAliyundriveRefreshtoken',
            CloudDrive_pb2.LoginAliyundriveRefreshtokenRequest,
            CloudDrive_pb2.APILoginResult,
        )
        self.APILoginAliyunDriveQRCode = grpclib.client.UnaryStreamMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/APILoginAliyunDriveQRCode',
            CloudDrive_pb2.LoginAliyundriveQRCodeRequest,
            CloudDrive_pb2.QRCodeScanMessage,
        )
        self.APILoginBaiduPanOAuth = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/APILoginBaiduPanOAuth',
            CloudDrive_pb2.LoginBaiduPanOAuthRequest,
            CloudDrive_pb2.APILoginResult,
        )
        self.APILoginOneDriveOAuth = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/APILoginOneDriveOAuth',
            CloudDrive_pb2.LoginOneDriveOAuthRequest,
            CloudDrive_pb2.APILoginResult,
        )
        self.ApiLoginGoogleDriveOAuth = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/ApiLoginGoogleDriveOAuth',
            CloudDrive_pb2.LoginGoogleDriveOAuthRequest,
            CloudDrive_pb2.APILoginResult,
        )
        self.ApiLoginGoogleDriveRefreshToken = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/ApiLoginGoogleDriveRefreshToken',
            CloudDrive_pb2.LoginGoogleDriveRefreshTokenRequest,
            CloudDrive_pb2.APILoginResult,
        )
        self.ApiLoginXunleiOAuth = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/ApiLoginXunleiOAuth',
            CloudDrive_pb2.LoginXunleiOAuthRequest,
            CloudDrive_pb2.APILoginResult,
        )
        self.ApiLogin123panOAuth = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/ApiLogin123panOAuth',
            CloudDrive_pb2.Login123panOAuthRequest,
            CloudDrive_pb2.APILoginResult,
        )
        self.APILogin189QRCode = grpclib.client.UnaryStreamMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/APILogin189QRCode',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.QRCodeScanMessage,
        )
        self.APILoginPikPak = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/APILoginPikPak',
            CloudDrive_pb2.UserLoginRequest,
            CloudDrive_pb2.APILoginResult,
        )
        self.APILoginWebDav = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/APILoginWebDav',
            CloudDrive_pb2.LoginWebDavRequest,
            CloudDrive_pb2.APILoginResult,
        )
        self.APIAddLocalFolder = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/APIAddLocalFolder',
            CloudDrive_pb2.AddLocalFolderRequest,
            CloudDrive_pb2.APILoginResult,
        )
        self.RemoveCloudAPI = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/RemoveCloudAPI',
            CloudDrive_pb2.RemoveCloudAPIRequest,
            CloudDrive_pb2.FileOperationResult,
        )
        self.GetAllCloudApis = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetAllCloudApis',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.CloudAPIList,
        )
        self.GetCloudAPIConfig = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetCloudAPIConfig',
            CloudDrive_pb2.GetCloudAPIConfigRequest,
            CloudDrive_pb2.CloudAPIConfig,
        )
        self.SetCloudAPIConfig = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/SetCloudAPIConfig',
            CloudDrive_pb2.SetCloudAPIConfigRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.GetSystemSettings = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetSystemSettings',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.SystemSettings,
        )
        self.SetSystemSettings = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/SetSystemSettings',
            CloudDrive_pb2.SystemSettings,
            google.protobuf.empty_pb2.Empty,
        )
        self.SetDirCacheTimeSecs = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/SetDirCacheTimeSecs',
            CloudDrive_pb2.SetDirCacheTimeRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.GetEffectiveDirCacheTimeSecs = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetEffectiveDirCacheTimeSecs',
            CloudDrive_pb2.GetEffectiveDirCacheTimeRequest,
            CloudDrive_pb2.GetEffectiveDirCacheTimeResult,
        )
        self.GetOpenFileTable = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetOpenFileTable',
            CloudDrive_pb2.GetOpenFileTableRequest,
            CloudDrive_pb2.OpenFileTable,
        )
        self.GetDirCacheTable = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetDirCacheTable',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.DirCacheTable,
        )
        self.GetReferencedEntryPaths = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetReferencedEntryPaths',
            CloudDrive_pb2.FileRequest,
            CloudDrive_pb2.StringList,
        )
        self.GetTempFileTable = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetTempFileTable',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.TempFileTable,
        )
        self.PushTaskChange = grpclib.client.UnaryStreamMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/PushTaskChange',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.GetAllTasksCountResult,
        )
        self.PushMessage = grpclib.client.UnaryStreamMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/PushMessage',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.CloudDrivePushMessage,
        )
        self.GetCloudDrive1UserData = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetCloudDrive1UserData',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.StringResult,
        )
        self.RestartService = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/RestartService',
            google.protobuf.empty_pb2.Empty,
            google.protobuf.empty_pb2.Empty,
        )
        self.ShutdownService = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/ShutdownService',
            google.protobuf.empty_pb2.Empty,
            google.protobuf.empty_pb2.Empty,
        )
        self.HasUpdate = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/HasUpdate',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.UpdateResult,
        )
        self.CheckUpdate = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/CheckUpdate',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.UpdateResult,
        )
        self.DownloadUpdate = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/DownloadUpdate',
            google.protobuf.empty_pb2.Empty,
            google.protobuf.empty_pb2.Empty,
        )
        self.UpdateSystem = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/UpdateSystem',
            google.protobuf.empty_pb2.Empty,
            google.protobuf.empty_pb2.Empty,
        )
        self.GetMetaData = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetMetaData',
            CloudDrive_pb2.FileRequest,
            CloudDrive_pb2.FileMetaData,
        )
        self.GetOriginalPath = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetOriginalPath',
            CloudDrive_pb2.FileRequest,
            CloudDrive_pb2.StringResult,
        )
        self.ChangePassword = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/ChangePassword',
            CloudDrive_pb2.ChangePasswordRequest,
            CloudDrive_pb2.FileOperationResult,
        )
        self.CreateFile = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/CreateFile',
            CloudDrive_pb2.CreateFileRequest,
            CloudDrive_pb2.CreateFileResult,
        )
        self.CloseFile = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/CloseFile',
            CloudDrive_pb2.CloseFileRequest,
            CloudDrive_pb2.FileOperationResult,
        )
        self.WriteToFileStream = grpclib.client.StreamUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/WriteToFileStream',
            CloudDrive_pb2.WriteFileRequest,
            CloudDrive_pb2.WriteFileResult,
        )
        self.WriteToFile = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/WriteToFile',
            CloudDrive_pb2.WriteFileRequest,
            CloudDrive_pb2.WriteFileResult,
        )
        self.GetPromotions = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetPromotions',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.GetPromotionsResult,
        )
        self.UpdatePromotionResult = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/UpdatePromotionResult',
            google.protobuf.empty_pb2.Empty,
            google.protobuf.empty_pb2.Empty,
        )
        self.GetCloudDrivePlans = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetCloudDrivePlans',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.GetCloudDrivePlansResult,
        )
        self.JoinPlan = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/JoinPlan',
            CloudDrive_pb2.JoinPlanRequest,
            CloudDrive_pb2.JoinPlanResult,
        )
        self.BindCloudAccount = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/BindCloudAccount',
            CloudDrive_pb2.BindCloudAccountRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.TransferBalance = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/TransferBalance',
            CloudDrive_pb2.TransferBalanceRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.ChangeEmail = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/ChangeEmail',
            CloudDrive_pb2.ChangeUserNameEmailRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.GetBalanceLog = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetBalanceLog',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.BalanceLogResult,
        )
        self.CheckActivationCode = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/CheckActivationCode',
            CloudDrive_pb2.StringValue,
            CloudDrive_pb2.CheckActivationCodeResult,
        )
        self.ActivatePlan = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/ActivatePlan',
            CloudDrive_pb2.StringValue,
            CloudDrive_pb2.JoinPlanResult,
        )
        self.CheckCouponCode = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/CheckCouponCode',
            CloudDrive_pb2.CheckCouponCodeRequest,
            CloudDrive_pb2.CouponCodeResult,
        )
        self.GetReferralCode = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetReferralCode',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.StringValue,
        )
        self.BackupGetAll = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/BackupGetAll',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.BackupList,
        )
        self.BackupAdd = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/BackupAdd',
            CloudDrive_pb2.Backup,
            google.protobuf.empty_pb2.Empty,
        )
        self.BackupRemove = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/BackupRemove',
            CloudDrive_pb2.StringValue,
            google.protobuf.empty_pb2.Empty,
        )
        self.BackupUpdate = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/BackupUpdate',
            CloudDrive_pb2.Backup,
            google.protobuf.empty_pb2.Empty,
        )
        self.BackupAddDestination = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/BackupAddDestination',
            CloudDrive_pb2.BackupModifyRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.BackupRemoveDestination = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/BackupRemoveDestination',
            CloudDrive_pb2.BackupModifyRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.BackupSetEnabled = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/BackupSetEnabled',
            CloudDrive_pb2.BackupSetEnabledRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.BackupSetFileSystemWatchEnabled = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/BackupSetFileSystemWatchEnabled',
            CloudDrive_pb2.BackupModifyRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.BackupUpdateStrategies = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/BackupUpdateStrategies',
            CloudDrive_pb2.BackupModifyRequest,
            google.protobuf.empty_pb2.Empty,
        )
        self.BackupRestartWalkingThrough = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/BackupRestartWalkingThrough',
            CloudDrive_pb2.StringValue,
            google.protobuf.empty_pb2.Empty,
        )
        self.CanAddMoreBackups = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/CanAddMoreBackups',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.FileOperationResult,
        )
        self.GetMachineId = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetMachineId',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.StringResult,
        )
        self.GetOnlineDevices = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/GetOnlineDevices',
            google.protobuf.empty_pb2.Empty,
            CloudDrive_pb2.OnlineDevices,
        )
        self.KickoutDevice = grpclib.client.UnaryUnaryMethod(
            channel,
            '/clouddrive.CloudDriveFileSrv/KickoutDevice',
            CloudDrive_pb2.DeviceRequest,
            google.protobuf.empty_pb2.Empty,
        )
